// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQkj5U-i-m8ixvkFKqMiqESBjVDN_IQY',
    appId: '1:579493321709:web:2dd28ae51ab7cc6f1aa5e4',
    messagingSenderId: '579493321709',
    projectId: 'serendib-trails',
    authDomain: 'serendib-trails.firebaseapp.com',
    storageBucket: 'serendib-trails.appspot.com',
    measurementId: 'G-315GWFTX1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ONFo-wvGFqqfaM933pSZ2dtb54BaYWA',
    appId: '1:579493321709:android:97d972d9264b41ab1aa5e4',
    messagingSenderId: '579493321709',
    projectId: 'serendib-trails',
    storageBucket: 'serendib-trails.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXgIcAFUKM2Pr94P4Lslg7jwKHSzTaRNI',
    appId: '1:579493321709:ios:8479096bdec297781aa5e4',
    messagingSenderId: '579493321709',
    projectId: 'serendib-trails',
    storageBucket: 'serendib-trails.appspot.com',
    iosBundleId: 'com.example.serendibTrails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXgIcAFUKM2Pr94P4Lslg7jwKHSzTaRNI',
    appId: '1:579493321709:ios:eabe157e2da444801aa5e4',
    messagingSenderId: '579493321709',
    projectId: 'serendib-trails',
    storageBucket: 'serendib-trails.appspot.com',
    iosBundleId: 'com.example.serendibTrails.RunnerTests',
  );
}
